/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceMyListingsRouteImport } from './routes/marketplace/my-listings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceMyListingsRoute = MarketplaceMyListingsRouteImport.update({
  id: '/marketplace/my-listings',
  path: '/marketplace/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/marketplace/my-listings': typeof MarketplaceMyListingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/marketplace/my-listings': typeof MarketplaceMyListingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/marketplace/my-listings': typeof MarketplaceMyListingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/marketplace/my-listings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/marketplace/my-listings'
  id: '__root__' | '/' | '/marketplace/my-listings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketplaceMyListingsRoute: typeof MarketplaceMyListingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/my-listings': {
      id: '/marketplace/my-listings'
      path: '/marketplace/my-listings'
      fullPath: '/marketplace/my-listings'
      preLoaderRoute: typeof MarketplaceMyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketplaceMyListingsRoute: MarketplaceMyListingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
